accounts:
  - name: alice
    coins: ["100000000uCVM", "10000000000000000000uMGT"]
  - name: bob
    coins: ["5000000000000uCVM"]
validator:
  name: alice
  staked: "100000000000000000000uCVM"
faucet:
  name: bob 
  coins: ["10uCVM"]
build:
  binary: "cvmd"
init:
  home: "$HOME/.cvmd"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "CVM_9000-1"
  app_state:
    staking:
      params:
        bond_denom: "uCVM"
    mint:
      params:
        mint_denom: "uCVM"
    crisis:
      constant_fee:
        denom: "uCVM"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "uCVM"
    evm:
      params:
        evm_denom: "uCVM" 
